# Generated by Django 2.1.1 on 2019-02-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='blog',
            name='pubdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
