# Generated by Django 2.1.1 on 2019-02-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190209_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pubdate',
            field=models.DateTimeField(),
        ),
    ]
